### ISSUE TITLE
How to access dogecoin daemon running in amazon AMI?

### ISSUE THREAD

**Issue by EMRJ** [repp/dogecoin_client#3]
I installed dogecoin daemon in amazon AMI(ubuntu 12.04), i want to access RPC calls from my localhost, still can't get connect with daemon sometimes results in Net::ReadTimeout: Net::ReadTimeout error

**Comment by repp** [comment]
I'm not familiar with AMI, but I'd suggest making sure that the port, host, username and password are correct. An easy way to make sure the client is configured correctly is to is to use the client's `.valid?` method. 

If you're trying to connect to a daemon running on a different machine you need to configure the daemon to accept outside connections. Try adding `rpcallowip=<your ip addres>` to the daemon config file. By default, dogecoind only accepts local connections. 

If your still having trouble, could you paste me the code you're using to connect and your daemon config file?

**Comment by EMRJ** [comment]
Thanks, rpcallowip did the trick
